param(
    [string]$ContractPath = "MockAPI/OpenApi/transport-canada.json",
    [string]$OutputPath = "MockAPI/Controllers/Generated"
)

$ErrorActionPreference = "Stop"
$httpMethods = @("get", "post", "put", "delete", "patch", "head", "options")
$attributeNames = @{
    get = "HttpGet"
    post = "HttpPost"
    put = "HttpPut"
    delete = "HttpDelete"
    patch = "HttpPatch"
    head = "HttpHead"
    options = "HttpOptions"
}

function ConvertTo-Identifier([string]$value) {
    $parts = [regex]::Matches($value, "[A-Za-z0-9]+") | ForEach-Object { $_.Value }
    $identifier = ($parts | ForEach-Object {
        if ($_.Length -eq 1) { $_.ToUpperInvariant() }
        else { $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1) }
    }) -join ""

    if ($identifier -match "^[0-9]") { return "N$identifier" }
    return $identifier
}

$contract = Get-Content -LiteralPath $ContractPath -Raw | ConvertFrom-Json
$operations = foreach ($pathProperty in $contract.paths.PSObject.Properties) {
    foreach ($operationProperty in $pathProperty.Value.PSObject.Properties) {
        if ($operationProperty.Name -notin $httpMethods) { continue }
        $tag = @($operationProperty.Value.tags)[0]
        if (-not $tag) { $tag = "Other" }
        [pscustomobject]@{
            Tag = $tag
            Method = $operationProperty.Name
            Route = $pathProperty.Name
        }
    }
}

New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
Get-ChildItem -LiteralPath $OutputPath -Filter "*Controller.cs" -File | Remove-Item -Force

foreach ($group in ($operations | Group-Object Tag | Sort-Object Name)) {
    $className = "$(ConvertTo-Identifier $group.Name)Controller"
    $usedNames = @{}
    $actions = foreach ($operation in $group.Group) {
        $routeName = $operation.Route.Trim("/") -replace "\{([^}]+)\}", "By`$1"
        $baseName = "$(ConvertTo-Identifier $operation.Method)$(ConvertTo-Identifier $routeName)"
        if ($usedNames.ContainsKey($baseName)) {
            $usedNames[$baseName]++
            $actionName = "$baseName$($usedNames[$baseName])"
        } else {
            $usedNames[$baseName] = 1
            $actionName = $baseName
        }

        $attribute = $attributeNames[$operation.Method]
        $verb = $operation.Method.ToUpperInvariant()
@"
    [$attribute("$($operation.Route)")]
    public IActionResult $actionName() => Mock("$verb", "$($operation.Route)");
"@
    }

    $content = @"
// <auto-generated />
using Microsoft.AspNetCore.Mvc;
using MockAPI.Mocking;

namespace MockAPI.Controllers.Generated;

[ApiController]
public sealed class $className(OpenApiMockCatalog catalog) : MockControllerBase(catalog)
{
$($actions -join "`r`n")
}
"@

    $filePath = Join-Path $OutputPath "$className.cs"
    Set-Content -LiteralPath $filePath -Value $content -Encoding UTF8
}

Write-Host "Generated $(@($operations).Count) actions across $(@($operations | Group-Object Tag).Count) controllers."
